[build]
  command = "yarn build"
  publish = "client/dist"
  functions = "backend"
  base = "client"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/:splat"
  status = 200
